version: '2'

services:

  base-dev:
    image: tislaamo/node:8
    tty: true
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app

  dev:
    extends:
      service: base-dev

  dev-network:
    extends:
      service: base-dev
    network_mode: bridge
    external_links:
      - vanilla-rpc:vanilla-rpc

  test-network:
    extends:
      service: base-dev
    network_mode: bridge
    external_links:
      - test-rpc:test-rpc

  servedocs:
    extends:
      service: base-dev
    command: yarn servedocs
    ports:
      - "3000:3000"
