version: '2'

services:

  base-dev:
    image: tislaamo/node:8
    tty: true
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app

  install:
    extends:
      service: base-dev
    command: yarn install

  dev:
    extends:
      service: base-dev
    command: yarn develop
    links:
      - ganache-cli
      - eth-explorer

  docs:
    extends:
      service: base-dev
    command: yarn docs

  servedocs:
    extends:
      service: base-dev
    command: yarn servedocs
    ports:
      - "3000:3000"

  test:
    extends:
      service: base-dev
    links:
      - ganache-cli
    command: yarn test

  coverage:
    extends:
      service: base-dev
    links:
      - ganache-cli
    command: yarn coverage

  coverage-explorer:
    extends:
      service: base-dev
    ports:
      - "8080:8080"
    command: yarn coverage-explorer

  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    networks:
      - default
    ports:
      - "8545:8545"

  eth-explorer:
    build:
      context: .
      dockerfile: docker/Dockerfile-eth-explorer
    ports:
      - "8000:8000"
