version: '2'

services:

  base-dev:
    image: tislaamo/node:8
    tty: true
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app

  install:
    extends:
      service: base-dev
    command: yarn install

  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    networks:
      - default
    ports:
      - "8545:8545"

  test:
    extends:
      service: base-dev
    links:
      - ganache-cli
    command: yarn test
  
  coverage:
    extends:
      service: base-dev
    links:
      - ganache-cli
    command: yarn coverage

  coverage-explorer:
    extends:
      service: base-dev
    ports:
      - "8080:8080"
    command: http-server coverage/
